<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>push on 배하람 블로그</title>
    <link>https://baeharam.github.io/tags/push/</link>
    <description>Recent content in push on 배하람 블로그</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>ko-KR</language>
    <managingEditor>hisfedev@gmail.com (배하람)</managingEditor>
    <webMaster>hisfedev@gmail.com (배하람)</webMaster>
    <lastBuildDate>Tue, 27 Aug 2019 14:31:45 +0900</lastBuildDate>
    
	<atom:link href="https://baeharam.github.io/tags/push/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>[GIT] 용량이 큰 파일을 삭제했는데도 push가 실패할 때</title>
      <link>https://baeharam.github.io/posts/git/gitfailed-to-push-large-file-after-deleted/</link>
      <pubDate>Tue, 27 Aug 2019 14:31:45 +0900</pubDate>
      <author>hisfedev@gmail.com (배하람)</author>
      <guid>https://baeharam.github.io/posts/git/gitfailed-to-push-large-file-after-deleted/</guid>
      <description>제목 그대로, 용량이 큰 파일을 올리다가 실패해서 삭제하고 다시 push했는데 실패하는 경우가 종종 있었다. 자주 이런 현상이 발생해서 해결법을 정리하고자 한다.
이런 현상이 발생하는 이유  Git stores the full history of your project, so even if you &amp;lsquo;delete&amp;rsquo; a file from your project, the Git repo still has a copy of the file in it&amp;rsquo;s history, and if you try to push to another repository (like one hosted at GitHub) then Git requires the remote repo has the same history that your local repo does (ie the same big files in it&amp;rsquo;s history).</description>
    </item>
    
  </channel>
</rss>